### ISSUE TITLE
Downloads of m4a are corupt or not saved properly?

### ISSUE THREAD

**Issue by eteipp70** [NotTobi/soundcloud-dl#16] opened 2021-04-13 04:22 UTC
I have run into quite a few files that have this problem. The files seem like the right size but do not play or open?

I toggled off the Download of the original version setting but no difference.

Here is the url to the files I was trying to get:
https://soundcloud.com/search/sounds?q=gorgon%20city&filter.duration=epic

[console-export-2021-4-12_23-8-30.txt](https://github.com/NotTobi/soundcloud-dl/files/6301207/console-export-2021-4-12_23-8-30.txt)

**Comment by NotTobi** [comment] 2021-04-13 19:37
Duplicate of #14.
I can't do anything about this, without investing major resources into this project. The .m4a files used by SoundCloud for some tracks appear to be broken. I think they strip parts from the file to save bandwidth. Their player can probably deal with it, but my plugin would have to reconstruct the file for a working download. ( Which is not a trivial tasks without insight into how SoundCloud deals with this)

What i can probably do over the weekend is add a functionality to just fallback to .mp3 automatically, so you don't need to go to the options and can still download the file.
Sorry for the inconvenience! :(

**Closed by NotTobi** 2021-04-13 19:37 UTC
