### ISSUE TITLE
Regression in v1.7.0 & v1.7.1: claims to have downloaded media file, but nothing happens

### ISSUE THREAD

**Issue by aCandidMind** [NotTobi/soundcloud-dl#7] opened 2020-07-26 23:15 UTC
Clicking the download button in version 1.7.0 and 1.7.1 starts the download animation and then claims to have downloaded the file. But actually not even a file save dialog appeared and Firefox didn't show any download activity.

Version 1.6.3 actually opens save dialog and downloads succesfully.

All of this is right after installing the addon.

Operating system is Windows 10 in this case, I can happily test with Kubuntu too.

**Comment by NotTobi** [comment] 2020-07-27 01:57
I can't reproduce this on my machine. :/
Are you sure you didn't enable silent downloads and that's why you're not seeing any save dialog?

![Settings page](https://user-images.githubusercontent.com/62906424/88495687-0781c300-cfbb-11ea-8cfc-6f00c1739207.png)

If the issue persists:
1. Restart your browser
2. Navigate to the extension debug view: 
about:devtools-toolbox?type=extension&id=%7Bc7a839e7-7086-4021-8176-1cfcb7f169ce%7D
(GitHub doesn't let me make a link out of this, so you'll have to copy and paste the URL into your browser)
3. Download a track from SoundCloud
4. Take a screenshot of the debug view and post it here, like this:
![Screenshot_20200727_035448](https://user-images.githubusercontent.com/62906424/88496279-ef12a800-cfbc-11ea-900f-1d19bf6e3792.png)

Also please include a link to the SoundCloud track you're seeing this issue with.

**Comment by gabhab** [comment] 2020-08-09 16:02
Not the original poster, but I came here to post the same thing. It's a reproducible error for me (running OS X), for example with this track:

[https://soundcloud.com/juanitasnyc/juanitas-mix-020-blacklauren-sponsored-by-the-long-count](url)

Here's a screenshot of the debug console. 

<img width="1457" alt="Screen Shot 2020-08-09 at 16 58 54" src="https://user-images.githubusercontent.com/6375274/89736536-01332280-da62-11ea-9614-2e4c8d31db34.png">

**Comment by NotTobi** [comment] 2020-08-09 16:45
Hi gabhab, with the track you linked I can reproduce it as well -  Thank you! :) 
Working on resolving this!

**Comment by NotTobi** [comment] 2020-08-09 17:41
Just published version 1.7.2, which should fix this issue. Please try it out and let me know whether I can close this issue or not! :)

**Comment by gabhab** [comment] 2020-08-09 20:04
Amazing, thank you - this fixes it! Thanks for the great extension, and thanks for fixing this so quickly.

**Closed** 2020-08-09 20:07 UTC
Labels: bug
